name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and test
        run: |
          cp .env.example .env
          docker-compose -f .github/workflows/github-actions-docker-compose.yml config --services   # This checks the configuration
          docker-compose -f .github/workflows/github-actions-docker-compose.yml up -d
          sleep 30
          docker-compose -f .github/workflows/github-actions-docker-compose.yml ps
          MYSQL_ROOT_PASSWORD=$(grep MYSQL_ROOT_PASSWORD .env | cut -d '=' -f2)
          docker-compose -f .github/workflows/github-actions-docker-compose.yml exec -T mysql mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --database="${MYSQL_DATABASE}" --execute="SELECT 1"

      - name: Clean up
        run: docker-compose -f .github/workflows/github-actions-docker-compose.yml down
